<?php

namespace Ddup\Payments\Test;

use Ddup\Payments\Helper\Application;
use Ddup\Payments\Test\TestCase;


class PaymentTest extends TestCase
{

    const pem_key      = __DIR__ . '/Providers/file/keypem.pem';
    const pem_key_prod = __DIR__ . '/Providers/file/keypem-prod.pem';

    /**
     * @var Application
     */
    protected $app;
    protected $open_alilog = false;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->app = new Application();
    }
}

